"""
simulation/task.py — Task (workload request) model.

Defines the Task dataclass used throughout the simulation.
Tasks are generated by the workload generator and consumed by
load-balancing algorithms in later phases.
"""

from dataclasses import dataclass, field
from typing import Optional

# ── Task Status constants ──────────────────────────────────────────────────────
STATUS_PENDING   = "Pending"
STATUS_RUNNING   = "Running"
STATUS_COMPLETED = "Completed"


@dataclass
class Task:
    """
    Represents a single computational task/request to be distributed.

    Attributes
    ----------
    task_id         : int           — Unique numeric identifier (1-based)
    name            : str           — Human-readable name, e.g. "T-1"
    size            : int           — Abstract task size (1–100 units)
    processing_req  : int           — Processing units required to execute
                                      (derived from size; same here for simplicity)
    arrival_order   : int           — Sequence number (arrival position)
    assigned_vm_id  : Optional[int] — ID of the VM this task is assigned to
                                      (None = unassigned)
    status          : str           — One of: Pending | Running | Completed
    """
    task_id        : int
    name           : str
    size           : int
    processing_req : int
    arrival_order  : int
    assigned_vm_id : Optional[int] = None
    status         : str           = STATUS_PENDING

    # ── State mutation helpers ─────────────────────────────────────────────────

    def assign(self, vm_id: int) -> None:
        """
        Assign this task to a VM.
        Called by load-balancing algorithms (Phase 3+).
        """
        self.assigned_vm_id = vm_id
        self.status = STATUS_RUNNING

    def complete(self) -> None:
        """Mark this task as completed (Phase 3+)."""
        self.status = STATUS_COMPLETED

    def reset(self) -> None:
        """Reset task to its initial Pending state."""
        self.assigned_vm_id = None
        self.status = STATUS_PENDING

    def to_dict(self) -> dict:
        """Serialise Task to a plain dictionary (useful for display tables)."""
        vm_label = f"VM-{self.assigned_vm_id}" if self.assigned_vm_id else "—"
        return {
            "Task"        : self.name,
            "Size"        : self.size,
            "Proc. Units" : self.processing_req,
            "Arrival #"   : self.arrival_order,
            "Status"      : self.status,
            "Assigned VM" : vm_label,
        }
